name: Docker Image CI

on: workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  REGISTRY_URL: https://registry.cn-shenzhen.aliyuncs.com
  REGISTRY_REPO: registry.cn-shenzhen.aliyuncs.com/cnmirror
  IMAGE_NAME: sampleweb-java-maven

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: https://registry.cn-shenzhen.aliyuncs.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t $REGISTRY_REPO/$IMAGE_NAME:$IMAGE_TAG .
        docker push $REGISTRY_REPO/$IMAGE_NAME:$IMAGE_TAG
